name: Make Release

on:
  workflow_dispatch:

jobs:
  make_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.8'
          bundler-cache: true
      - name: Make Release
        run: |
          bundle install
          bundle exec fastlane make_release
