name: Make Release

on:
  workflow_dispatch:

jobs:
  make_release:
    runs-on: macos-15 
    steps:
      - uses: actions/checkout@v4
      - name: Make Release
        run: |
          bundle install
          bundle exec fastlane make_release
