name: Make Release

on:
  workflow_dispatch:

jobs:
  make_release:
    runs-on: macos-15 
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CACTUS_GH_WORKFLOW_PAT }}
      - name: Make Release
        run: |
          bundle install
          bundle exec fastlane make_release_branch
