name: Run All Test

on:
  push:
    branches:
      - main
      - "releases/**"
  pull_request:
    branches:
      - main
      - "releases/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-all-tests:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v1
      - name: List Xcode Versions
        run: ls /Applications | grep Xcode
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.3.app
      - name: List all simulators
        run: xcrun simctl list
      - name: Run all tests on iOS
        run: |
          bundle install
          bundle exec fastlane run_all_tests
